
services:
  api:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
  
  # client:
  #   build: ./client
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./client:/usr/src/app
  #   networks:
  #     - default
  #   depends_on:
  #     - api

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    restart: always
    ports:
      - 5432:5432
